### ISSUE TITLE
Create common time function

### ISSUE THREAD

**Issue by prensing** [ligerbots/InfiniteRecharge2021#3]
Our code calls System.nanoTime() in a few places (mostly in the old Commands). This provides a time stamp in (integer) nanoseconds. However, nsec are not useful units, so we always convert to seconds.

Create a function to just provide the time in seconds, as a floating point number. Replace any existing calls to "nanoTime" (plus of course the conversion). Probably should be a static method of Robot.

**Comment by dwillins** [comment]
I'll take a crack at this one
