### ISSUE TITLE
Make a DeployIntake command

### ISSUE THREAD

**Issue by coachFitz0807** [ligerbots/InfiniteRecharge2021#45]
Start with TestShoulder on the shoulderFixes branch. Delete everything in Climber.periodic(). Rename TestShoulder to DeployIntake. In the execture() method, it has to raise the shoulder slightly to release the holder and then go down as the TestShoulder command does now.

**Comment by prensing** [comment]
There are also some other routines in Climber which should be cleaned out, since they are explicitly tied to the code in periodic().

**Comment by YJ-7274** [comment]
I made the changes, also created a pull request
